name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: $

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@burak.gur'
      - run: yarn publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: $
